Packer Homework
Otus-DevOps-22-08/humster88_infra pull request #4
Opened 2022-09-26 01:13 UTC by humster88

# Выполнено ДЗ №5

 - [ Написан параметризованный из файла с переменными packer/variables.json шаблон создания наполовину настроенного образа ВМ packer/ubuntu16.json] Основное ДЗ
 - [1. Написан параметризованный из файла с переменными packer/files/immutable_variables.json шаблон создания полностью настроенного и готового к деплою образа ВМ packer/immutable.json
2. Написан скрипт config-scripts/create-reddit-vm.sh, который создает ВМ с помощью Yandex.Cloud CLI из полностью подготовленного образа из предыдущего пункта ] Задание со *

## В процессе сделано:
1. Написан параметризованный из файла с переменными packer/variables.json шаблон создания наполовину настроенного образа ВМ packer/ubuntu16.json
2. Написан параметризованный из файла с переменными packer/files/immutable_variables.json шаблон создания полностью настроенного и готового к деплою образа ВМ packer/immutable.json
3. Написан скрипт config-scripts/create-reddit-vm.sh, который создает ВМ с помощью Yandex.Cloud CLI из полностью подготовленного образа из пункта 2

## Как запустить проект:
Из директории packer
1. packer build -var-file variables.json ubuntu16.json
2. packer build -var-file files/immutable_variables.json immutable.json
3. ../config-scripts/create-reddit-vm.sh
## Как проверить работоспособность:
 - перейти по ссылке http://51.250.64.138:9292/

## PR checklist
 - [ +] Выставил label с номером домашнего задания
 - [ +] Выставил label с темой домашнего задания

2022-09-26 07:16 UTC, humster88 commented
Просьба подсказать почему не проходит тест.
Локально все ок, см. скрин
![image](https://user-images.githubusercontent.com/80584663/192215667-a6c247f1-f82b-46f9-bc63-73a283e7fdd2.png)

2022-09-26 13:35 UTC, mrgreyves requested changes
Здравствуйте!)
У вас ключик находится не в той директории
Перенесите его на уровень выше
Приключение на 5 минут =)

2022-09-26 15:05 UTC, humster88 commented
> Здравствуйте!) У вас ключик находится не в той директории Перенесите его на уровень выше Приключение на 5 минут =)
@mrgreyves 
А объясните, плз. почему не в той? ключик в packer, манифест в packer. локально структура такая же, но все работает

2022-09-27 11:37 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу

2022-09-27 11:37 UTC, mrgreyves commented on packer/variables.json.example
> +  "service_account_key_file": "./key.json",
Уберите ./

2022-09-27 11:37 UTC, mrgreyves commented on packer/variables.json.example
> +  "service_account_id": "1q1q1q1q1qq1q13e3e3e",
service_account_id по идеи не нужен так как файл ключика используется

2022-09-27 11:50 UTC, humster88 commented
Спасибо, как исправить было и с начала примерно понятно.
Меня интересовало почему разное поведение?
Локально все работает, выше скрин.
1. сам параметр допустим, внесен опционально, в соответствии с заданием
2. ./ означает текущую директорию, но тут дело было не в этом, это корректно отрабатывало, проблема почему-то именно при использовании параметра service_account_id

2022-09-27 16:44 UTC, mrgreyves approved these changes
Здравствуйте!)
Скорее всего история связана с тем что используются два метода авторизации одновременно =)

2022-09-27 17:03 UTC, humster88 commented
> Здравствуйте!) Скорее всего история связана с тем что используются два метода авторизации одновременно =)

Но локально-то все то же самое, но работает)

2022-09-27 17:04 UTC, merged