Ansible-2 HW
Otus-DevOps-22-08/humster88_infra pull request #8
Opened 2022-11-05 19:35 UTC by humster88

# Выполнено ДЗ №

 - [ x ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
- Используем плейбуки, хендлеры и шаблоны для конфигурации
окружения и деплоя тестового приложения. Подход один плейбук, один
сценарий (play)
- Аналогично один плейбук, но много сценариев
- И много плейбуков.
- Изменим провижн образов Packer на Ansible-плейбуки

## Как запустить проект:
 - ansible-playbook site.yml в директории ansible

## Как проверить работоспособность:
 - http://%ip_of_app_instance%:9292

## PR checklist
 - [ x ] Выставил label с номером домашнего задания
 - [ x ] Выставил label с темой домашнего задания

2022-11-05 20:17 UTC, humster88 commented
@mrgreyves 
![image](https://user-images.githubusercontent.com/80584663/200139267-d86c9a01-e2c2-45d8-a32e-e6ffdb73b0ae.png)

2022-11-06 13:06 UTC, mrgreyves requested changes
Здравствуйте!)
Проверил ваше дз
Добавьте фейковый ключик для пакера, приключение на 5 минут =)

2022-11-06 18:44 UTC, humster88 commented
> Здравствуйте!) Проверил ваше дз Добавьте фейковый ключик для пакера, приключение на 5 минут =)

Добрый день.
Поправил

2022-11-07 15:04 UTC, humster88 commented
> > Здравствуйте!) Проверил ваше дз Добавьте фейковый ключик для пакера, приключение на 5 минут =)
> 
> Добрый день. Поправил

смержить-то можно?)

2022-11-08 12:03 UTC, mrgreyves approved these changes
Здравствуйте!)
Да, можно =)

2022-11-08 14:11 UTC, merged